const quizData = {
    courseTitle: "Cybersecurity",
    'tutorial-1': {
        title: "tutorial-1",
        data: [
            { type: 'mcq', q: "Cybersecurity is defined as the ongoing effort to protect:", options: ["a) Physical attacks on computer hardware.", "b) Individuals, organizations, and governments from digital attacks.", "c) Only government secrets and national security data.", "d) Data on local, disconnected systems."], correct: 1 },
            { type: 'mcq', q: "Protecting your identity, data, and computing devices falls under which level of cybersecurity?", options: ["a) Organizational", "b) Government", "c) Personal", "d) National"], correct: 2 },
            { type: 'mcq', q: "The protection of an organization's reputation, data, and customers is the responsibility at which cybersecurity level?", options: ["a) Personal", "b) Government", "c) Organizational", "d) Public"], correct: 2 },
            { type: 'mcq', q: "Personal data is defined as any information that can be used to identify you, and it exists:", options: ["a) Only online.", "b) Only offline.", "c) Both offline and online.", "d) Only on social media platforms."], correct: 2 },
            { type: 'mcq', q: "Which statement is TRUE regarding an online identity?", options: ["a) You only have an online identity if you have social media accounts.", "b) You do not have an online identity if you only read physical books.", "c) If you use the web, you have an online identity.", "d) Online identity only refers to your email address."], correct: 2 },
            { type: 'mcq', q: "Which username option is the safest choice for an online identity?", options: ["a) jane.doe", "b) jdoe.IT", "c) jdoe", "d) j.doe12", "e) jdoe2004"], correct: 2 },
            { type: 'mcq', q: "When choosing a username for your online identity, it is important to avoid:", options: ["a) A simple and appropriate name.", "b) Something respectful.", "c) Revealing any personal information.", "d) Using a common name."], correct: 2 },
            { type: 'mcq', q: "Which of the following is NOT listed as a type of personal data that can compromise your privacy?", options: ["a) Social security number", "b) Medical records", "c) Educational records", "d) Historical fiction novels you read"], correct: 3 },
            { type: 'mcq', q: "The main risk of cybercriminals accessing sensitive personal information is that they can use it to:", options: ["a) Find your physical address only.", "b) Identify and impersonate you.", "c) Send you spam emails.", "d) Check your credit score."], correct: 1 },
            { type: 'mcq', q: "If a friend posts a photo you shared with them online, where does your data now primarily reside?", options: ["a) Only in the country where your friend lives.", "b) On your friend's external hard drive.", "c) On servers located in different parts of the world.", "d) Only on your own device."], correct: 2 },
            { type: 'mcq', q: "Once data is shared online, you lose control over its location and:", options: ["a) It is automatically deleted from your device.", "b) The friend is solely responsible for its security.", "c) People whom you don't even know may gain access to it.", "d) It is instantly protected by international law."], correct: 2 },
            { type: 'mcq', q: "The rise of smart devices and digital convenience comes with the cost of:", options: ["a) Increased battery usage.", "b) Less personalized advertising.", "c) Privacy.", "d) Slower internet speeds."], correct: 2 },
            { type: 'mcq', q: "How do social media companies primarily generate income?", options: ["a) Selling premium subscriptions.", "b) Providing technical support services.", "c) Selling targeted advertising based on customer data.", "d) Creating their own hardware devices."], correct: 2 },
            { type: 'mcq', q: "The most immediate goal of cybercriminals (hackers) is typically to get your:", options: ["a) Physical mailing address.", "b) Money.", "c) Personal opinions.", "d) Social media passwords."], correct: 1 },
            { type: 'mcq', q: "Besides short-term financial gain, what long-term goal are cybercriminals invested in?", options: ["a) Selling their own software.", "b) Gaining political power.", "c) Identity theft.", "d) Improving system security."], correct: 2 },
            { type: 'mcq', q: "Which entity tracks your online activity and can sell this data to advertisers?", options: ["a) Your Internet Service Provider (ISP)", "b) Government defense agencies", "c) Antivirus software companies", "d) Your bank"], correct: 0 },
            { type: 'mcq', q: "Websites use 'cookies' primarily to:", options: ["a) Monitor your computer's health.", "b) Track your activities to provide a more personalized experience.", "c) Encrypt all data transmission.", "d) Block targeted advertising."], correct: 1 },
            { type: 'mcq', q: "Search engines and social media platforms gather your information primarily to:", options: ["a) Improve system performance.", "b) Sell this information to advertisers for a profit.", "c) Provide better customer service.", "d) Satisfy government regulations only."], correct: 1 },
            { type: 'mcq', q: "Which of the following is considered 'Traditional data' for organizations?", options: ["a) Big Data and IoT sensor readings.", "b) Intellectual property.", "c) Personal fitness tracking data.", "d) Social media search histories."], correct: 1 },
            { type: 'mcq', q: "IoT (Internet of Things) and Big Data are associated with:", options: ["a) Only financial records.", "b) Only physical paper records.", "c) A large network of connected physical objects, sensors, and software.", "d) Traditional transactional data."], correct: 2 },
            { type: 'mcq', q: "Which of the following is NOT a level of cybersecurity?", options: ["a) Personal", "b) Organizational", "c) Government", "d) International"], correct: 3 },
            { type: 'mcq', q: "Which of the following qualifies as personal data?", options: ["a) Your favorite movie", "b) Your social security number", "c) Random website cookies", "d) A public news article"], correct: 1 },
            { type: 'mcq', q: "“Online” refers to:", options: ["a) Reading a physical book", "b) Shopping at a local store", "c) Being connected and accessible via the internet", "d) Watching a movie offline"], correct: 2 },
            { type: 'mcq', q: "Which of the following is a false belief people often have about online identity?", options: ["a) If you don’t use social media, you don’t have an online identity", "b) Using the web creates an online identity", "c) Online identity exists even without accounts", "d) All internet users leave a digital footprint"], correct: 0 },
            { type: 'mcq', q: "Which of the following is NOT considered personal data?", options: ["a) Medical records", "b) Educational records", "c) Employment records", "d) Online advertisements"], correct: 3 },
            { type: 'mcq', q: "Why is safeguarding personal data important?", options: ["a) To reduce internet costs", "b) To prevent identity theft and misuse by cybercriminals", "c) To increase storage capacity", "d) To get faster online services"], correct: 1 },
            { type: 'mcq', q: "Which of these is an example of a smart device collecting data?", options: ["a) Traditional wristwatch", "b) Smartwatch fitness tracker", "c) Physical notebook", "d) Landline phone"], correct: 1 },
            { type: 'mcq', q: "What is identity theft?", options: ["a) Using another person’s name for fun", "b) Long-term misuse of someone’s personal information", "c) Creating a fake username online", "d) Accidentally losing your ID card"], correct: 1 },
            { type: 'mcq', q: "Why do advertisers want your data?", options: ["a) To improve your education", "b) To send targeted ads based on your preferences", "c) To block your online activity", "d) To reduce internet usage"], correct: 1 },
            { type: 'mcq', q: "Why is cybersecurity important for organizations?", options: ["a) To increase internet speed", "b) To prevent falling victim to cybercrime", "c) To reduce electricity costs", "d) To avoid hiring IT staff"], correct: 1 },
            { type: 'mcq', q: "Whose responsibility is cybersecurity in an organization?", options: ["a) Only the IT department", "b) Everyone in the organization", "c) The CEO alone", "d) Only the government"], correct: 1 }
        ]
    }
};
